package com.brandon3055.townbuilder;

import com.brandon3055.brandonscore.BrandonsCore;
import com.brandon3055.brandonscore.registry.ModFeatureParser;
import com.brandon3055.townbuilder.schematics.SchematicHandler;
import com.brandon3055.townbuilder.schematics.commands.CommandHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper;

import java.util.Arrays;

@Mod(modid = TownBuilder.MODID, name = TownBuilder.MODNAME, version = TownBuilder.VERSION, dependencies = "required-after:brandonscore@[" + BrandonsCore.VERSION + ",);")
public class TownBuilder {
    public static final String MODID = "townbuilder";
    public static final String MODNAME = "Town Builder";
    public static final String RPREFIX = MODID.toLowerCase() + ":";
    public static final String VERSION = "${mod_version}";

    public static final String networkChannelName = "TownBuilderC";
    public static SimpleNetworkWrapper network;

    @Mod.Instance(MODID)
    public static TownBuilder instance;

    @SidedProxy(clientSide = "com.brandon3055.townbuilder.client.ClientProxy", serverSide = "com.brandon3055.townbuilder.CommonProxy")
    public static CommonProxy proxy;

    public static ModFeatureParser featureParser;

    @Mod.EventHandler
    public void serverLoad(FMLServerStartingEvent event) {
        CommandHandler.init(event);
    }

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        ModFeatureParser.registerModFeatures(MODID);
//        Configuration configuration = new Configuration(new File(FileHandler.brandon3055Folder, "TownBuilder/TownBuilder.cfg"));

//        ConfigHandler.init(configuration);

        event.getModMetadata().autogenerated = false;
        event.getModMetadata().credits = "";
        event.getModMetadata().description = "This is a small mod that adds the ability for map makers and server owners to create a plot system that allows players to bye houses and/or other structures";
        event.getModMetadata().authorList = Arrays.asList("brandon3055");
        event.getModMetadata().logoFile = "";
        event.getModMetadata().url = "http://www.tolkiencraft.com/";
        event.getModMetadata().version = VERSION + "-MC1.12.2";

        proxy.registerRendering();
        proxy.initializeNetwork();
        SchematicHandler.init(event);
    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent event) {
        proxy.registerListeners();
        proxy.registerServerListeners();
    }
}
